sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - stable
before_script:
  - rm package-lock.json # Man, I hate npm for this.
  - npm i -S express jsonwebtoken
script:
  - npm test
branches:
  only:
  - master
  - /^feature\/.{3,}$/
